package com.jackattackk246.files.ui

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import com.example.util.WatchFileItem
import com.jackattackk246.files.model.*
import com.jackattackk246.files.ui.theme.AppThemeMode
import com.jackattackk246.files.util.*


@Composable
fun CardSizeController(
    currentSize: CardSizeProfile,
    onSizeChange: (CardSizeProfile) -> Unit,
    onMoveUp: (() -> Unit)?,
    onMoveDown: (() -> Unit)?,
    onRemoveCard: () -> Unit
) {}

@Composable
fun ShortcutPanelTile(
    icon: ImageVector,
    label: String,
    accentColor: Color,
    cardContainer: Color,
    cardBorder: Color,
    primaryTextColor: Color = Color.Transparent,
    onClick: () -> Unit,
    modifier: Modifier = Modifier
) {}

@Composable
fun RecycleBinPanel(
    themeMode: AppThemeMode,
    customAccentColor: Color?,
    onDismiss: () -> Unit
) {}

@Composable
fun WatchStorageBrowserDialog(
    path: String,
    items: List<WatchFileItem>,
    primaryTextColor: Color = Color.Transparent,
    secondaryTextColor: Color,
    accentColor: Color,
    cardContainer: Color,
    cardBorder: Color,
    onDismiss: () -> Unit,
    onNavigateSubdir: (String) -> Unit
) {}

@Composable
fun DeepAnalyzerDialog(
    primaryTextColor: Color = Color.Transparent,
    secondaryTextColor: Color,
    accentColor: Color,
    cardContainer: Color,
    cardBorder: Color,
    onDismiss: () -> Unit
) {}
@Composable fun DeviceStorageMeterWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun InternalStorageRestoredWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun DownloadRestoredWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun MainStorageRestoredWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun RecycleBinRestoredWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun ApksInstallerRestoredWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun OfflineCompressionStudioWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun DuplicateFileInspectorWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun ApkPackageExtractorWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun ZeroFillShredderWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun SmartFlashAnalyzerWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun DiskDefragmenterTrimWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun PartitionImageCreatorWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun AdsTrackerDetectorWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun ExifMetadataScrubberWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun SymlinkTerminalDirectorWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun FileTriageEngineWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun RansomwareSandboxGuardWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun HeavyFileCompactorWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
@Composable fun PinnedShortcutWidget(cardContainer: Color = Color.Transparent, cardBorder: Color = Color.Transparent, primaryTextColor: Color = Color.Transparent, secondaryTextColor: Color = Color.Transparent, accentColor: Color = Color.Transparent, physicalMetrics: Any? = null, sizeMode: Any? = null, size: Any? = null, isLight: Boolean = false, customDiagnosticText: String? = null, overrideUsedRatio: Float? = null, onFormatPartition: (() -> Unit)? = null, onNavigateToSettings: (() -> Unit)? = null, onNavigateToExplorer: Any? = null, trashedCount: Int = 0, onOpenRecycleBin: (() -> Unit)? = null, themeMode: AppThemeMode = AppThemeMode.SYSTEM, onRequireDevAuth: (() -> Unit)? = null, config: Any? = null, showHiddenFiles: Boolean = false, isCompactMode: Boolean = false, isGridView: Boolean = false, onOpenOtgDetails: (() -> Unit)? = null, onOpenWatchStorage: (() -> Unit)? = null, onToggleHiddenFiles: (() -> Unit)? = null, onOpenDeepAnalyzer: (() -> Unit)? = null, onPurgeEmptyFolders: (() -> Unit)? = null, onToggleCompactMode: (() -> Unit)? = null, onToggleGridView: (() -> Unit)? = null, onWearSync: (() -> Unit)? = null, title: String = "", path: String = "") {}
